### ISSUE TITLE
Clean up settings vs. configuration vs. preferences

### ISSUE THREAD

**Issue by savannidgerinel** [luminescent-dreams/fitnesstrax#92]
There are three different data structures all for the same thing, and which don't necessarily mesh together. Devise a way to clean them up.

**Comment by m0n0chr0m3** [comment]
I'm interested in tackling this issue.

Before I submit any PR, let's coordinate on what needs to happen. What I've discovered already is this:
- The code in [`src/preferences.rs`](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/preferences.rs) doesn't appear to be in use. I can delete the file without impacting the unit tests, nor the execution of the GTK-based GUI app.
- The distinction between the code in [`src/config.rs`}(https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/config.rs) and the one in [`src/settings.rs`](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/settings.rs) seems sensible: the former deals only with reading out the configuration file, the latter deals with run-time concers. This distinction can perhaps be made a bit more concrete by moving all parsing/string-validation to the `Configuration`, but beyond that I think both have a valid reason for existing.
- In general, the possibility for errors due to parsing/string-validation should probably be purged from the core code, by pushing the failure cases to the boundaries (file or GUI input). As a concrete example: the chain of `set_units`-calls which determines which `UnitSystem` is in place currently uses a `&str` to name the unit system. If an invalid string is passed, this causes an error [deep down in the call-stack](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/settings.rs#L38). If instead [the widget in `src/components/preferences.rs`](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/components/preferences.rs#L105) would perform the conversion, all internal code could use the type-safe `UnitSystem`. The error-condition then needs to be handled earlier, and in this specific case it turns out the error shouldn't even be reachable.
- The `UnitSystem` of a `Settings` object is stored twice: once as [a direct field](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/settings.rs#L10), and once inside [its `i18n::Text`-field](https://github.com/luminescent-dreams/fitnesstrax/blob/e4a7d3ec5d4c1f8f9fe13857cad55893dc2bc5bc/src/settings.rs#L19). I think it's reasonable to
    - remove the direct field,
    - modify `Settings::set_units` to assign to `self.text.units` (i.e., the field inside the `Text`) instead, and
    - add a `Setting::units`-method which returns `self.text.units`.
 As far as I can tell, a `Text`'s `units`-field may be modified at-will; no consistency between the `units` and the `language` or `bundle` need to be maintained. Perhaps the name of `Text` needs to be changed, though. It groups all internationalization settings, not just those related to text.
- On the GUI-side, both `src/components/preferences.rs` and `src/components/setting.rs` exist. Here, the latter doesn't appear to be in use. In any case, it only deals with a singular "setting", so it's not of interest to this issue #92.

As always, as a sanity-check I implemented the changes discussed above in [a branch of my fork of Fitnesstrax](https://github.com/m0n0chr0m3/fitnesstrax/commit/543f42a6184c489ec837b3f579b0cf4c1bb6015f). In that code I also [implemented](https://github.com/m0n0chr0m3/fitnesstrax/commit/543f42a6184c489ec837b3f579b0cf4c1bb6015f#diff-b4628cc5ef9bf2617976114d1eda0f13R42) (de-)serialize on `UnitSystem`, so that the `Configuration` type [can contain a `UnitSystem`](https://github.com/m0n0chr0m3/fitnesstrax/commit/543f42a6184c489ec837b3f579b0cf4c1bb6015f#diff-6d8a5e2104954a026de2bfe2b936aea4R15) instead of a unit system `&str`. My reasoning was that `Configuration` should do the parsing/string-validation; once you have a `Configuration` object, building a `Settings` object should be infallible. This goal is not achieve in the current state of my branch, as constructing a `LanguageIdentifier` from the `language` string of a `Configuration` [may still fail](https://github.com/m0n0chr0m3/fitnesstrax/commit/543f42a6184c489ec837b3f579b0cf4c1bb6015f#diff-7e30a274b7e58a9d8bf644a467c7e044R15).

Do you have any concerns/hints/remarks/... I need to address before continuing?

**Comment by savannidgerinel** [comment]
This is incredibly good research.

My biggest concern is that I'm doing massive refactorings across the GUI side of the application today, in particular related to https://github.com/luminescent-dreams/fitnesstrax/issues/88. It may be natural for me to take on this task, as part of that work, since the preferences/settings GUI will be one of those components that I need to revisit.

So, please hold off until I have had another week of working on things.

**Comment by savannidgerinel** [comment]
Also, please install the Zenhub plugin for your browser. I would like to know if you can see the Zenhub board for this project. That will give you better insight into how I am prioritizing the workflow on these projects.

**Comment by m0n0chr0m3** [comment]
Sure, the branch I linked was meant as a throw-away, exploratory first stab at the issue. You can perhaps incorporate some of the changes into your FRP-ification, but by means of rewriting it rather than by merging the branch.

I hadn't seen the article, as I stayed away from the GUI-sounding issues (and yet I ended up in the GUI code anyway. Not too surprising, I guess, when touching the code of a GUI application). The approach you outline seems well thought out, I'm looking forward to see how you make it work. On the other hand, respectfully, I think it needs saying that wrangling GTK into the RP paradigm might be too much work for one person who'd rather be writing their fitness tracker application. It would seem that [vgtk](https://crates.io/crates/vgtk) has a very similar roadmap to what you're going for, so perhaps cooperation could be useful. (Do note that vgtk is licensed under LGPL-3.0+.) A more mature RP-on-GTK+ option exists too in the form of [relm](https://crates.io/crates/relm), but I think that one already existed when you started off, so perhaps you've considered it before and written it off. (Saving you a click: it has an MIT license.)

Zenhub seems to want me to register using my GitHub account. I'm not sure I sufficiently agree with their Terms and Conditions to do that. I'll look into the option of creating a separate account; at first sight I can live with the Terms and Conditions if I accept them from an clean account.

**Comment by savannidgerinel** [comment]
Don't worry about the Zenhub, then. It was a think I didn't know about, and having multiple accounts can be a pain.

Anyway, I'm going to take this task on over the next day or two, as it should now be rather easy given the changes that I've made. The refactoring is as done as I think it is going to be for now.

I did not know about either of those libraries, so I will definitely check out both of them once I have the application feature complete and am satisfied with the look and feel of the application.
